### PR TITLE
Tackling Todo #3

### PR DESCRIPTION
**Pull request by chiefsmurph**
- React.createClass -> ES6 Class extending Component
- stripped down unnecessary state
- added support for proximity, filterTypes, bbox and limit Mapbox querystring filters as optional props

### CODE REVIEW

**Comment by travisdmathis** [comment]
@chiefsmurph can you fix your merge conflicts before we can merge.

**Comment by chiefsmurph** [comment]
no problem @travisdmathis. should be good to go.

**Comment by chiefsmurph** [comment]
closing PR

**Comment by travisdmathis** [comment]
@chiefsmurph i would like to commit this, if you would still like it committed and use it as opensource contributions..

**Comment by chiefsmurph** [comment]
@travisdmathis glad to hear you appreciated this PR.  wish we could have been able to merge in more code like this for Localvore Today but I guess not.

**Pull request closed without merging**
